language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
install: make install
script: make test
after_success:
    - coveralls
